if (! require("plotGoogleMaps") ) {
  install.packages("plotGoogleMaps")
  library(plotGoogleMaps)
}

if (! require("RColorBrewer") ) {
  install.packages("RColorBrewer")
  library(RColorBrewer)
}


##### USER INPUTS 
###settings
display_map <- %%display_map%%
legend_field <- "%%identif_legend%%"
legend_type <- %%legend_type%%
number_colors <- %%number_colors%%
  
###plot settings
mapTypeId <- %%type_map%% #HYBRID (default), TERRAIN, SATELLITE or ROADMAP
color_palette <- "%%color_palette%%"
reverse_color_palette <- %%reverse_color_palette%%
text_size <- %%text_size%%
display_text <- "%%display_text%%"
display_text <- strsplit(display_text, split='\n', fixed=TRUE)[[1]][1]
marker_scale <- as.numeric(%%marker_scale%%)
point_style <-  %%type_point%% #normal or name_only
use_custom_directory <- %%use_custom_directory%%
  
  ###advanced settings
  EPSG_code <- %%EPSG_code%% #if unknown, should be 4326 (googleMaps)
  layerName <- "%%layer_name%%"



if (nchar(legend_field)==0) {
  # adding a dummy legend
  modelerData <- data.frame(modelerData, legend=rep(" ", dim(modelerData)[1]))  
  use_legend <- FALSE
  legend_field <- "legend"
} else {
  use_legend <- TRUE
}

# the column to be plotted is legend_field
zcol <- legend_field

# printing a warning if there are missing values
missing_coord <- is.na(modelerData$`%%identif_lat%%`) | is.na(modelerData$`%%identif_lat%%`)
if (any(missing_coord)) {
  warning("Rows with missing coordinates were not plotted")
}
missing_legend <- is.na(modelerData[,legend_field])
if (any(missing_legend))
{
  warning("Rows with missing legend were not plotted")
}

# removing rows with missing data
modelerData <- modelerData[ !missing_legend & !missing_coord , ]

if(legend_type=="categorical") {
  modelerData[,legend_field] <- factor(modelerData[,legend_field])   
  number_colors <- length(levels(modelerData[,legend_field]))
} else if (legend_type=="numeric") {
  if(number_colors<0) {
    stop("Invalid number of colors selected")
  }
}

# convert to SPDF
coordinates(modelerData)<-~`%%identif_lon%%`+`%%identif_lat%%`

# adding Coordinate Referent Sys.
#google maps uses epsg code 4326
proj4string(modelerData) <- CRS( paste('+init=epsg:', EPSG_code, sep="") )

if(use_custom_directory) {
  filepath <- "%%custom_directory%%"
  if(nchar(filepath)==0) {
    stop("Please provide a valid file path to save the output")
  }
} else {
  filepath <- paste( tempfile(), ".htm", sep='')
}

#setting the working dir to the same path as where the htm map will be saved
#allows the legend to be displayed correctly
working_dir <- dirname(filepath)
setwd(working_dir)


if(display_map) {
  openMap <- TRUE
} else {
  openMap <- FALSE
}


if(point_style=="normal") {
  icon <- TRUE
} else if (point_style=="text_only"){
  icon <- FALSE
}

# setting default color palettes
if(color_palette == "default") {
  if(legend_type=="categorical") {
    color_palette <- "Set1"
  } else if (legend_type == "numeric") {
    color_palette <- "Blues"
  }
}

# the color palette from brewer.pal have a maximum number of color, depending on the palette.
# if we ask for too many colors, a warning is printed and a smaller umber of colors is returned.
# but the palette is extended afterwards anyway so the warning is useless.
message("Please discard any warning 'n too large' from brewer.pal")

# generating the chosen color palette
# if a "mono" color is chosen, the colorPalette is only one color
if(grepl("mono", color_palette, fixed=TRUE)) {
  # if mono, we extract the wanted color (color_palette format is "mono color")
  colPalette <- strsplit(color_palette, ' ', fixed=TRUE)[[1]][2]
} else {
   # else, the selected palette is not mono
   # this is not possible if there is no legend
   if(use_legend==FALSE) {
        colPalette <- "steelblue" #monochrome blue if no legend
   } else {
     # if there is a legend we generate the colorBrewer palette
      colPalette <- brewer.pal(n=min(12, number_colors), name=color_palette)
      if(reverse_color_palette) {
            colPalette <- rev(colPalette)
      }
   }
}

#extending the color palette to the wanted number of colors
# here colPalette can be a single color (mono) or a serie of colors generated by brewer.pal
colPalette <- colorRampPalette(colPalette)(number_colors)

text_size <- if(display_text=="TRUE" || (point_style=="text_only")) text_size else 0

if(is.null(colPalette)) {
  ic=iconlabels(modelerData@data[[legend_field]], height=text_size, icon=icon, scale=marker_scale )
} else { 
  ic=iconlabels(modelerData@data[[legend_field]], height=text_size, colPalette=colPalette, icon=icon, scale=marker_scale)
}

if(nchar(layerName)==0) 
  layerName <- paste(legend_field, "layer")

m <- plotGoogleMaps(
  modelerData, zcol=zcol, 
  layerName=layerName, 
  mapTypeId=mapTypeId, 
  filename=filepath, 
  iconMarker=ic, 
  colPalette=colPalette, 
  openMap=FALSE)

if(openMap) {
  browseURL(filepath)
}
